Add support for building with CMake
SYZYGYfpga/avr-dna-fw pull request #3
Opened 2022-01-08 13:18 UTC by twam

2022-01-18 21:53 UTC, hayhut requested changes
Hello and thank you for contributing to SYZYGYfpga! I just had a few suggestions. Otherwise, this is great stuff and we appreciate all of your recent contributions.

2022-01-18 21:53 UTC, hayhut commented on CMakeLists.txt
> +set(AVRDUDE_PROGRAMMER avrispmkII CACHE STRING "Programmer")
Edit readme to describe what to change in order to target a different AVR programmer.

2022-01-18 21:53 UTC, hayhut commented on README.md
> +Alternatively the firmware can be built using [CMake](https://cmake.org)
Edit readme to describe a general process for what a user would do with the CMake file and how to use it (commands, etc).

2022-01-19 16:59 UTC, twam commented
Hey @hayhut,

I extended the documentation in the README. Let me know if it's still unclear.

2022-01-19 22:38 UTC, hayhut requested changes
Two tiny suggestions, and then this looks good to merge!

2022-01-19 22:38 UTC, hayhut commented on README.md
> +https://github.com/SYZYGYfpga/avr-dna-fw.git
```suggestion
git clone https://github.com/SYZYGYfpga/avr-dna-fw.git
```

2022-01-19 22:38 UTC, hayhut commented on README.md
> +To program the firmware run
```suggestion
To program the firmware run:
```

2022-01-20 11:22 UTC, twam commented on README.md
> +https://github.com/SYZYGYfpga/avr-dna-fw.git
🙈

2022-01-20 16:35 UTC, hayhut approved these changes
Thanks again! This will be merged soon.

2022-01-20 16:57 UTC, merged